### ISSUE TITLE
there's no code

### ISSUE THREAD

**Issue by nstickney** [usma-eecs/dargle#1]
I came to this website expecting a dark web search engine. Instead you give me this box of nothing, @kylekyle. Which means @dshawth is apt to try and fill this box of nothing with a dark web search engine... which means more projects.

![Vader Noooo](https://media1.giphy.com/media/LSmULmByAQHQs/giphy.gif)

**Comment by Yashinex** [comment]
There is now code, and the project is functional at https://www.dargle.net

Issue closed.
